services:
  php:
    image: ghcr.io/florentdestremau/symfony-chat-app:master
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=sqlite:////storage/data_prod.db
      - MERCURE_URL=http://localhost/.well-known/mercure
      - MERCURE_PUBLIC_URL=https://symfony-chat-app.once.florent.cc/.well-known/mercure
      - MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      - APP_SECRET=${APP_SECRET:-!ChangeThisAppSecretKey!}
    volumes:
      - sqlite_data:/storage
    healthcheck:
      test: ["CMD", "php", "-r", "exit(false === @file_get_contents('http://localhost:80') ? 1 : 0);"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
